<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>volumixctl</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Volumix.Core/Volumix.Core.csproj" />
    <ProjectReference Include="../Volumix.Application/Volumix.Application.csproj" />
    <ProjectReference Include="../Volumix.Infrastructure/Volumix.Infrastructure.csproj" />
    <ProjectReference Include="../Volumix.Platform.Linux/Volumix.Platform.Linux.csproj" />
    <ProjectReference Include="../Volumix.NativeInterop/Volumix.NativeInterop.csproj" />
  </ItemGroup>
</Project>
