<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>fadrio</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="../Fadrio.Core/Fadrio.Core.csproj" />
    <ProjectReference Include="../Fadrio.Application/Fadrio.Application.csproj" />
    <ProjectReference Include="../Fadrio.Infrastructure/Fadrio.Infrastructure.csproj" />
    <ProjectReference Include="../Fadrio.Platform.Linux/Fadrio.Platform.Linux.csproj" />
    <ProjectReference Include="../Fadrio.NativeInterop/Fadrio.NativeInterop.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="../../assets/branding/raster/fadrio-app-icon-monochrome.png"
                      Link="Assets/fadrio-app-icon.png" />
  </ItemGroup>
</Project>
