<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>volumix</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="../Volumix.Core/Volumix.Core.csproj" />
    <ProjectReference Include="../Volumix.Application/Volumix.Application.csproj" />
    <ProjectReference Include="../Volumix.Infrastructure/Volumix.Infrastructure.csproj" />
    <ProjectReference Include="../Volumix.Platform.Linux/Volumix.Platform.Linux.csproj" />
    <ProjectReference Include="../Volumix.NativeInterop/Volumix.NativeInterop.csproj" />
  </ItemGroup>
</Project>
